import { v4 as uuid } from "uuid";

import {
  cap1,
  cap2,
  cap3,
  cap4,
  cap5,
  cap6,
  cap7,
  cap8,
  shoe1,
  shoe2,
  shoe3,
  shoe4,
  shoe5,
  shoe6,
  shoe7,
  shoe8,
  shoe9,
  shoe10,
  glasses1,
  glasses2,
  glasses3,
  glasses4,
  glasses5,
  glasses6,
  glasses7,
  glasses8,
  glasses9,
  glasses10,
} from "../../assets";

export const products = [
  {
    _id: uuid(),
    title: "Nike",
    imgSrc: cap1,
    subtitle: "Embroidered cap",
    brand: "Nike",
    price: "500",
    categoryName: "caps",
    gender: "men",
    rating: 2,
  },
  {
    _id: uuid(),
    title: "Adidas",
    imgSrc: cap2,
    subtitle: "Synthetic white cap",
    brand: "Adidas",
    price: "900",
    categoryName: "caps",
    gender: "men",
    rating: 4,
  },
  {
    _id: uuid(),
    title: "H&M",
    imgSrc: cap3,
    subtitle: "Embroidered cap",
    brand: "H&M",
    price: "700",
    categoryName: "caps",
    gender: "men",
    rating: 3,
  },
  {
    _id: uuid(),
    title: "H&M",
    imgSrc: cap4,
    subtitle: "Regular white cap",
    brand: "H&M",
    price: "700",
    categoryName: "caps",
    gender: "women",
    rating: 4,
  },
  {
    _id: uuid(),
    title: "Adidas",
    imgSrc: cap5,
    subtitle: "Casual Black cap",
    brand: "Adidas",
    price: "700",
    categoryName: "caps",
    gender: "men",
    rating: 5,
  },
  {
    _id: uuid(),
    title: "H&M",
    imgSrc: cap6,
    subtitle: "Embroidered cap",
    brand: "H&M",
    price: "700",
    categoryName: "caps",
    gender: "men",
    rating: 2,
  },
  {
    _id: uuid(),
    title: "H&M",
    imgSrc: cap7,
    subtitle: "Text print cap",
    brand: "H&M",
    price: "700",
    categoryName: "caps",
    gender: "men",
    rating: 2,
  },
  {
    _id: uuid(),
    title: "Nike",
    imgSrc: cap8,
    subtitle: "Text print dual color cap",
    brand: "Nike",
    price: "700",
    categoryName: "caps",
    gender: "women",
    rating: 2,
  },
  {
    _id: uuid(),
    title: "Adidas",
    imgSrc: shoe1,
    subtitle: "Arsenal ZX 2K boost2.0",
    brand: "Adidas",
    price: "7000",
    categoryName: "shoes",
    gender: "men",
    rating: 4,
  },
  {
    _id: uuid(),
    title: "Nike",
    imgSrc: shoe2,
    subtitle: "Air Max Dawn",
    brand: "Nike",
    price: "700",
    categoryName: "shoes",
    gender: "women",
    rating: 4,
  },
  {
    _id: uuid(),
    title: "Nike",
    imgSrc: shoe3,
    subtitle: "Air Max 90 SE",
    brand: "Nike",
    price: "9000",
    categoryName: "shoes",
    gender: "men",
    rating: 3,
  },
  {
    _id: uuid(),
    title: "H&M",
    imgSrc: shoe4,
    subtitle: "Casual shoes",
    brand: "H&M",
    price: "700",
    categoryName: "shoes",
    gender: "men",
    rating: 2,
  },
  {
    _id: uuid(),
    title: "Nike",
    imgSrc: shoe5,
    subtitle: "Casual shoes",
    brand: "Nike",
    price: "1499",
    categoryName: "shoes",
    gender: "men",
    rating: 2,
  },
  {
    _id: uuid(),
    title: "Nike",
    imgSrc: shoe6,
    subtitle: "Sneakers",
    brand: "Nike",
    price: "3700",
    categoryName: "shoes",
    gender: "women",
    rating: 2,
  },
  {
    _id: uuid(),
    title: "Nike",
    imgSrc: shoe7,
    subtitle: "Sports shoes",
    brand: "Nike",
    price: "2999",
    categoryName: "shoes",
    gender: "women",
    rating: 4,
  },
  {
    _id: uuid(),
    title: "Adidas",
    imgSrc: shoe8,
    subtitle: "Fluoroscent shoes",
    brand: "Adidas",
    price: "8999",
    categoryName: "shoes",
    gender: "men",
    rating: 4,
  },
  {
    _id: uuid(),
    title: "H&M",
    imgSrc: shoe9,
    subtitle: "Casual white shoes",
    brand: "H&M",
    price: "4999",
    categoryName: "shoes",
    gender: "men",
    rating: 3,
  },
  {
    _id: uuid(),
    title: "Adidas",
    imgSrc: shoe10,
    subtitle: "Sneakers X14597",
    brand: "Adidas",
    price: "2499",
    categoryName: "shoes",
    gender: "men",
    rating: 2,
  },
  {
    _id: uuid(),
    title: "Ray Ban",
    imgSrc: glasses1,
    subtitle: "MH140 Hiking glasses",
    brand: "Ray Ban",
    price: "700",
    categoryName: "glasses",
    gender: "men",
    rating: 5,
  },
  {
    _id: uuid(),
    title: "H&M",
    imgSrc: glasses2,
    subtitle: "Aviator sunglasses",
    brand: "H&M",
    price: "999",
    categoryName: "glasses",
    gender: "women",
    rating: 3,
  },
  {
    _id: uuid(),
    title: "Ray Ban",
    imgSrc: glasses3,
    subtitle: "Cool sunglasses",
    brand: "Ray Ban",
    price: "1499",
    categoryName: "glasses",
    gender: "men",
    rating: 3,
  },
  {
    _id: uuid(),
    title: "Ray Ban",
    imgSrc: glasses4,
    subtitle: "Cateye sunglasses",
    brand: "Ray Ban",
    price: "4999",
    categoryName: "glasses",
    gender: "women",
    rating: 5,
  },
  {
    _id: uuid(),
    title: "H&M",
    imgSrc: glasses5,
    subtitle: "Butterfly glasses",
    brand: "H&M",
    price: "399",
    categoryName: "glasses",
    gender: "women",
    rating: 2,
  },
  {
    _id: uuid(),
    title: "H&M",
    imgSrc: glasses6,
    subtitle: "Stylish cateye sunglasses",
    brand: "H&M",
    price: "1299",
    categoryName: "glasses",
    gender: "women",
    rating: 3,
  },
  {
    _id: uuid(),
    title: "Nike",
    imgSrc: glasses7,
    subtitle: "Round glasses",
    brand: "Nike",
    price: "700",
    categoryName: "glasses",
    gender: "men",
    rating: 4,
  },
  {
    _id: uuid(),
    title: "Ray Ban",
    imgSrc: glasses8,
    subtitle: "Square sunglasses",
    brand: "Ray Ban",
    price: "1899",
    categoryName: "glasses",
    gender: "men",
    rating: 4,
  },
  {
    _id: uuid(),
    title: "H&M",
    imgSrc: glasses9,
    subtitle: "Cateye sunglasses",
    brand: "H&M",
    price: "1499",
    categoryName: "glasses",
    gender: "women",
    rating: 2,
  },
  {
    _id: uuid(),
    title: "Ray Ban",
    imgSrc: glasses10,
    subtitle: "Square sunglasses",
    brand: "Ray Ban",
    price: "699",
    categoryName: "glasses",
    gender: "men",
    rating: 4,
  },
];
